name: Run Plan on OCI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'oci/**'
jobs:
  run-terragrunt-plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_oci_user: ${{ secrets.OCI_USER }}
      TF_VAR_oci_tenancy: ${{ secrets.OCI_TENANCY }}
      TF_VAR_oci_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      TF_VAR_oci_region: ${{ secrets.OCI_REGION }}
    steps:
      - uses: actions/checkout@v4
      - name: save private key
        run: echo "${{ secrets.OCI_PRIVATE_KEY }}" > ./oci/private_key.pem
      - name: Set up Aqua CLI
        uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.35.0
      - name: Terragrunt Init
        working-directory: ./oci
        run: terragrunt init
      - name: Terragrunt Plan
        working-directory: ./oci
        env:
          TF_VAR_oci_private_key_path: ./private_key.pem
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod 755 $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh
          terragrunt run-all plan --terragrunt-non-interactive --terragrunt-tfpath $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh
